### ISSUE TITLE
eslint parsing error for vue files

### ISSUE THREAD

**Issue by fragx1011** [ZachJW34/nx-plus#120] opened 2020-11-06 01:21 UTC
## Current Behavior
webstorm and vscode report error when openning vue files

## Expected Behavior
should work correctly

## Steps to Reproduce
create a new apps using nx cli
open the file using webstorm or vscode with eslint support

### Failure Logs
`Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/pages/auth/home.page.vue.
The file must be included in at least one of the projects provided.`

![image](https://user-images.githubusercontent.com/71076673/98314678-c98f3480-1fd6-11eb-8e8d-5234ca181b91.png)

### Environment

Plugin name and version: 

`  @nrwl/cli : 10.3.1
  @nrwl/cypress : 10.3.1
  @nrwl/eslint-plugin-nx : 10.3.1
  @nrwl/express : Not Found
  @nrwl/jest : 10.3.1
  @nrwl/linter : 10.3.1
  @nrwl/nest : 10.3.1
  @nrwl/next : Not Found
  @nrwl/node : 10.3.1
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 10.3.1
  typescript : 4.0.5
`

**Comment by BuckyMaler** [comment] 2020-11-07 20:11
I cannot reproduce the error after generating a new Nx workspace and Vue app. Please provide a minimal reproduction of the error. FYI, I'm using VS Code.

**Comment by fragx1011** [comment] 2020-11-08 13:49
Hmm, just tried to create a new app using nx vue, its working propertly, i don't know exactly how it happened in my project.
I didn't modify any config file inside vue apps folder, just worked normally on my app adding new vue file/service ect ..

is there a way to print stack why error is happening?

**Comment by BuckyMaler** [comment] 2020-11-08 21:15
As far as printing a stack trace, the [`debug`](https://eslint.org/docs/user-guide/command-line-interface#-debug) option may be helpful, but [Nx](https://github.com/nrwl/nx/blob/10.3.1/docs/angular/api-linter/builders/eslint.md) doesn't surface that option.

If your repository is public, please provide a link to it. Otherwise, please provide the following information:

What version of `@nx-plus/vue` are you using?
What version of `vue` are you using?
Your project's configuration in workspace.json/angular.json.
Your project's `tsconfig.app.json`.

**Comment by fragx1011** [comment] 2020-11-11 06:17
Hey sure, here is the link to the repo

https://github.com/fragx1011/etudesnet

**Comment by BuckyMaler** [comment] 2020-11-14 21:31
I cloned your repo and was still unable to reproduce the error. Perhaps like you mentioned it may have been a temporary issue with your ESLint extension.

I'm going to close this issue, but if you're able to reproduce the error I can reopen it.

**Closed by BuckyMaler** 2020-11-14 21:31 UTC
Labels: bug
