### ISSUE TITLE
ForkTsCheckerWebpackPlugin configuration has an unknown property 'tsconfig'.

### ISSUE THREAD

**Issue by alvarosaburido** [ZachJW34/nx-plus#97] opened 2020-09-04 08:29 UTC
## Current Behavior
```
An unhandled exception occurred: Invalid configuration object. ForkTsCheckerWebpackPlugin has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tsconfig'. These properties are valid:
   object { async?, typescript?, eslint?, formatter?, issue?, logger? }
```

## Expected Behavior
Vue app is served normally

## Steps to Reproduce
Update deps in vue app to. (To use latest [vue-devtools](https://github.com/vuejs/vue-devtools))
```
"vue": "^3.0.0-rc.10"
"@vue/cli-plugin-typescript": "~4.5.4",
"@vue/cli-service": "~4.5.4",
"@vue/compiler-sfc": "3.0.0-rc.10",
```

**Comment by alvarosaburido** [comment] 2020-09-09 13:57
Hi!, so we manage to make Vue 3 work inside of the monorepo, but latest `"@vue/cli-plugin-typescript": "~4.5.4" have a breaking change https://github.com/vuejs/vue-cli/commit/1aaa59264235b83cb1e2700ab2cf3aa04b40c907#diff-5bd90b2d73b2975144503cb89f9bc5ba  for the `fork-ts-checker-webpack-plugin-v5`

**Comment by BuckyMaler** [comment] 2020-09-12 05:09
If you cannot reproduce this using Vue 2, then I'm going to close this issue. I described a workaround for this [here](https://github.com/ZachJW34/nx-plus/pull/99#issuecomment-691411542).

**Closed** 2020-09-15 03:50 UTC
Labels: bug
